[package]
name = "paraphase-plugin"
description = "Plugin authoring helpers for Paraphase"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
paraphase-core.workspace = true
